version: '3.8'

services:
  web:
    env_file:
      - .env
    build: .
    restart: always
    environment:
      TZ: "Europe/Istanbul"
    command: python wsgi.py runserver 0.0.0.0:5000
    networks:
      docker_network_host_monitor:
        ipv4_address: 172.21.1.9
    volumes:
      - .:/usr/app/
    ports:
      - 5000:5000

networks:
  docker_network_host_monitor:
    ipam:
      driver: default
      config:
        - subnet: 172.21.0.0/16
